GestureAnywhere: Migrate to LineageParts
Change-Id: I9e835654dcb5ad086126f26a2749bf2525c99b56

GA_WIP

Change-Id: I2964028eaf06f6f738be319a7ebaf8ba2efaef74

GestureAnywhere: remove units as it seems to not work

packages/apps/LineageParts/res/layout/profiles_header.xml:18: warn: generated id 'android:id/title' for external package 'android'.
packages/apps/LineageParts/res/xml/gesture_anywhere.xml:75: error: attribute com.android.settings:units not found.
packages/apps/LineageParts/res/xml/gesture_anywhere.xml:84: error: attribute com.android.settings:units not found.
packages/apps/LineageParts/res/xml/gesture_anywhere.xml:93: error: attribute com.android.settings:units not found.
error: failed linking file resources.

Change-Id: Ic42033339514a838afeb4892f20b3b378bc09a4c

Revert "GestureAnywhere: remove units as it seems to not work"

This reverts commit 829f4d5d7fd82611027f6e6b9216ef873e278cfc.

GA: Fix typo

Change-Id: I66c33affedd0ea384f5e284b931d87ab940655ed

GA: Implement units

Change-Id: I4f0e01b07926caffb6cd851f67267b5c349a8074

GA: Fixup attrs

Change-Id: Ifcff125a03b4483e92a1399f766c1b0153f08092

GestureAnywhere: Cleanup layout

Change-Id: I1bbf21a70f223fdda7e44c98bbab2b761259418a

GA: Fix typo ..again

Change-Id: Ibbc14a214764b36b5effac97dceafde7cbbe1886