GestureAnywhere [2/3]
Change-Id: I18ac09696cac82845b9a358df94f93bcbd9970d9
Signed-off-by: varund7726 <date.varun123@gmail.com>

Build custom vendor support [1/2]

GestureAnywhere: Add ShortcutPickHelper

Change-Id: I97b0a2b14ae21b84ee872eb3f866b6872a22815d

GestureAnywhere: Remove the LinearLayout style

Change-Id: I52012b321dff9dae61b54c4e6af3b3d50bf3311d

GestureAnywhere: Change the accent color of the icon

Change-Id: I37e4946e3e0498b5c8586b8b30b3a16f9022f58b

GestureAnywhere: Use VendorSupport-preference

GestureAnywhere: Migrate to androidx

Change-Id: Ic79d59398ba6130f6583f04e2c3ea907491a8140

GestureAnywhere: Do not clear gesture after drawing

GestureAnywhere: Use system accent color

GestureAnywhere: Migrate to LineageParts

Change-Id: I9e835654dcb5ad086126f26a2749bf2525c99b56

GA_WIP

Change-Id: I2964028eaf06f6f738be319a7ebaf8ba2efaef74

GestureAnywhere: remove units as it seems to not work

packages/apps/LineageParts/res/layout/profiles_header.xml:18: warn: generated id 'android:id/title' for external package 'android'.
packages/apps/LineageParts/res/xml/gesture_anywhere.xml:75: error: attribute com.android.settings:units not found.
packages/apps/LineageParts/res/xml/gesture_anywhere.xml:84: error: attribute com.android.settings:units not found.
packages/apps/LineageParts/res/xml/gesture_anywhere.xml:93: error: attribute com.android.settings:units not found.
error: failed linking file resources.

Change-Id: Ic42033339514a838afeb4892f20b3b378bc09a4c

Revert "GestureAnywhere: remove units as it seems to not work"

This reverts commit 829f4d5d7fd82611027f6e6b9216ef873e278cfc.

GA: Fix typo

Change-Id: I66c33affedd0ea384f5e284b931d87ab940655ed

GA: Implement units

Change-Id: I4f0e01b07926caffb6cd851f67267b5c349a8074

GA: Fixup attrs

Change-Id: Ifcff125a03b4483e92a1399f766c1b0153f08092

GestureAnywhere: Cleanup layout

Change-Id: I1bbf21a70f223fdda7e44c98bbab2b761259418a

GA: Fix typo ..again

Change-Id: Ibbc14a214764b36b5effac97dceafde7cbbe1886

GestureAnywhere: Use LineageSettings

Change-Id: I511b920b94fe708ff670aebf7e2fb351ceb10a0b

GestureAnywhere: Edit XML values

Change-Id: I8e18f2ee1f8c498cff5cdbaa70514052022064c5

GestureAnywhere: Add Icons from RR

Change-Id: Ia1293f148b9255651029548307c3b3b19f4ad7ff

Revert "GestureAnywhere: Do not clear gesture after drawing"

* Implemented this in fwb

This reverts commit d9fcd49b26bf2f125d68b3c19d87f3f2121305d7.

Change-Id: I1e817b391a79150e19fa059124b7cd888d41ca54

Co-authored-by: DroidFreak32 <rushabshah32@gmail.com>
Change-Id: I4738f80a0406e52611ddbccf4781012d32bf2dc7